service: aws-node-http-api-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

plugins:
  - serverless-offline

functions:
  pets:
    handler: handler.pets
    events:
      - httpApi:
          path: /pets
          method: get
